theme: jekyll-theme-leap-day

title: Handbook of the Society of California Archivists
description: The SCA Handbook is intended to be a practical tool outlining the major duties of the officers, Board of Directors, and committees. It provides an up-to-date reference on the Corporation’s structure, aims, policies, and procedures.
